name: Generate Scorecards Reminders
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
jobs:
  generate-scorecards-reminders:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel:
          - SLACK_WEBHOOK_URL_CHANNEL_1
          - SLACK_WEBHOOK_URL_CHANNEL_2
    steps:
      - name: Generate Scorecards Reminder for ${{ matrix.channel }}
        uses: port-labs/port-sender@v0.2.4
        with:
          operation_kind: scorecard_reminder
          port_client_id: ${{ secrets.PORT_CLIENT_ID }}
          port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
          slack_webhook_url: ${{ secrets[matrix.channel] }}
          blueprint: bitbucketRepository
          scorecard: Ownership
          filter_rule: '{"property": "$","operator": "isNotEmpty"}'
          target_kind: slack
